### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by itsmeabacus** [11philip22/twitter_media_downloader#3]
AttributeError: module 'urltools' has no attribute 'extract'

**Comment by 11philip22** [comment]
Hi man. Sorry for the late response. I havnt touched this project in months but ill see if i can fix her up for you. With what version of python are you trying to run it?

**Comment by itsmeabacus** [comment]
3.6

**Comment by 11philip22** [comment]
Could you try updating your Python to 3.7+ This project is written in Python 3.7. I just checked and my urltools definitely has a function extract.
